import { initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { getMessaging } from "firebase-admin/messaging";
import { HttpsError, onCall } from "firebase-functions/v2/https";
initializeApp(); const db=getFirestore();
const text=(v:unknown,max=500)=>typeof v==="string"?v.trim().replace(/[<>]/g,"").slice(0,max):"";
const admin=(role:unknown)=>role==="admin"||role==="superadmin";
const audit=async(uid:string,action:string,target:string)=>db.collection("adminAuditLog").add({uid,action,target,createdAt:FieldValue.serverTimestamp()});
export const setAccountRole=onCall({enforceAppCheck:true},async(req)=>{if(!req.auth||req.auth.token.role!=="superadmin")throw new HttpsError("permission-denied","Restricted action.");const uid=text(req.data.uid,128),role=text(req.data.role,16);if(!uid||!["donor","requester","admin","superadmin"].includes(role))throw new HttpsError("invalid-argument","Invalid account role.");await getAuth().setCustomUserClaims(uid,{role});await audit(req.auth.uid,"set-role",uid);return {ok:true};});
export const reviewDonor=onCall({enforceAppCheck:true},async(req)=>{if(!req.auth||!admin(req.auth.token.role))throw new HttpsError("permission-denied","Restricted action.");const uid=text(req.data.uid,128),status=text(req.data.status,16),reason=text(req.data.reason);if(!uid||!["approved","rejected"].includes(status))throw new HttpsError("invalid-argument","Invalid review.");await db.collection("users").doc(uid).update({verificationStatus:status,verificationReason:reason,verifiedAt:FieldValue.serverTimestamp(),verifiedBy:req.auth.uid});await db.collection("donors").doc(uid).set({verified:status==="approved"},{merge:true});await audit(req.auth.uid,"review-donor",uid);return {ok:true};});
export const sendEmergencyRequest=onCall({enforceAppCheck:true},async(req)=>{if(!req.auth)throw new HttpsError("unauthenticated","Sign in required.");const since=Date.now()-15*60_000, recent=await db.collection("requests").where("requesterId","==",req.auth.uid).where("createdAt",">",new Date(since)).get();if(!recent.empty)throw new HttpsError("resource-exhausted","Please wait before sending another emergency alert.");const requestId=text(req.data.requestId,128);const request=await db.collection("requests").doc(requestId).get();if(!request.exists||request.data()?.requesterId!==req.auth.uid)throw new HttpsError("permission-denied","Request not found.");const group=text(request.data()?.bloodGroup,4);const donors=await db.collection("donors").where("available","==",true).where("verified","==",true).where("bloodGroup","in",compatibleDonors(group)).limit(500).get();const tokens=donors.docs.map(d=>text(d.data().fcmToken,512)).filter(Boolean);if(tokens.length)await getMessaging().sendEachForMulticast({tokens,notification:{title:"Emergency blood request",body:`Compatible ${group} blood is urgently needed in Nankana Sahib.`},data:{requestId}});await db.collection("requests").doc(requestId).update({sos:true,sosRadiusKm:5,sosSentAt:FieldValue.serverTimestamp()});return {notified:tokens.length};});
function compatibleDonors(recipient:string){const map:Record<string,string[]>={"AB+":["A+","A-","B+","B-","AB+","AB-","O+","O-"],"AB-":["A-","B-","AB-","O-"],"A+":["A+","A-","O+","O-"],"A-":["A-","O-"],"B+":["B+","B-","O+","O-"],"B-":["B-","O-"],"O+":["O+","O-"],"O-":["O-"]};return map[recipient]||[];}
