package com.ishark.bloodbanknankana

import android.content.Intent
import android.os.Bundle
import android.content.Context
import android.content.res.Configuration
import java.util.Locale
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.google.firebase.FirebaseApp
import com.google.firebase.appcheck.FirebaseAppCheck
import com.google.firebase.appcheck.playintegrity.PlayIntegrityAppCheckProviderFactory
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.PhoneAuthOptions
import com.google.firebase.auth.PhoneAuthProvider
import com.ishark.bloodbanknankana.data.FirebaseRepository
import com.ishark.bloodbanknankana.data.Hospital
import com.ishark.bloodbanknankana.ui.theme.BloodBankTheme
import java.util.concurrent.TimeUnit

class MainActivity: ComponentActivity() {
 override fun onCreate(state:Bundle?) { super.onCreate(state); FirebaseApp.initializeApp(this); FirebaseAppCheck.getInstance().installAppCheckProviderFactory(PlayIntegrityAppCheckProviderFactory.getInstance()); setContent { BloodBankTheme { App() } } }
}
private enum class Screen { LANGUAGE, AUTH, HOME, PROFILE, REQUEST, DIRECTORY, SETTINGS, ABOUT }
@Composable private fun App() { var screen by remember { mutableStateOf(Screen.LANGUAGE) }; val repo=remember{FirebaseRepository()}; val signedIn=FirebaseAuth.getInstance().currentUser!=null
 LaunchedEffect(signedIn){ if(signedIn) screen=Screen.HOME }; Surface { when(screen) { Screen.LANGUAGE->Language { screen=Screen.AUTH }; Screen.AUTH->Auth { screen=Screen.HOME }; Screen.HOME->Home({screen=it}); Screen.PROFILE->Profile(repo){screen=Screen.HOME}; Screen.REQUEST->Request(repo){screen=Screen.HOME}; Screen.DIRECTORY->Directory(repo); Screen.SETTINGS->Settings(repo,{screen=Screen.ABOUT},{screen=Screen.LANGUAGE}); Screen.ABOUT->About() } } }
@Composable private fun Page(title:String, back:(()->Unit)?=null, content:@Composable ColumnScope.()->Unit) { Scaffold(topBar={TopAppBar(title={Text(title,fontWeight=FontWeight.SemiBold)},navigationIcon={if(back!=null) IconButton(back){Icon(Icons.Outlined.ArrowBack,null)} })}){p->Column(Modifier.padding(p).padding(20.dp).fillMaxSize(),verticalArrangement=Arrangement.spacedBy(16.dp),content=content)} }
@Composable private fun Language(done:()->Unit) { val context=LocalContext.current; var selected by remember{mutableStateOf(context.getSharedPreferences("settings",Context.MODE_PRIVATE).getString("language","en") ?: "en")}; Page(stringResource(R.string.choose_language)){ RadioRow(stringResource(R.string.english),selected=="en"){selected="en"}; RadioRow(stringResource(R.string.roman_urdu),selected=="ur"){selected="ur"}; Spacer(Modifier.weight(1f)); Button({ context.getSharedPreferences("settings",Context.MODE_PRIVATE).edit().putString("language",selected).apply(); val configuration=Configuration(context.resources.configuration); configuration.setLocale(Locale(if(selected=="ur") "ur" else "en", if(selected=="ur") "PK" else "")); context.resources.updateConfiguration(configuration,context.resources.displayMetrics); done() },modifier=Modifier.fillMaxWidth()){Text(stringResource(R.string.continue_label))}; TextButton(done,Modifier.align(Alignment.CenterHorizontally)){Text(stringResource(R.string.about))} } }
@Composable private fun RadioRow(text:String, active:Boolean, click:()->Unit)=Row(Modifier.fillMaxWidth().clickable(onClick=click),verticalAlignment=Alignment.CenterVertically){RadioButton(active,click);Text(text)}
@Composable private fun Auth(done:()->Unit) { val auth=FirebaseAuth.getInstance(); var phone by remember{mutableStateOf("")}; var code by remember{mutableStateOf("")}; var verificationId by remember{mutableStateOf<String?>(null)}; var error by remember{mutableStateOf("")}; val invalidPhone=stringResource(R.string.invalid_phone); val failed=stringResource(R.string.verification_failed)
 Page(stringResource(R.string.welcome)){ Text(stringResource(R.string.welcome_body)); OutlinedTextField(phone,{phone=it},label={Text(stringResource(R.string.phone_hint))},singleLine=true); if(verificationId!=null)OutlinedTextField(code,{code=it},label={Text(stringResource(R.string.verification_code))},singleLine=true); if(error.isNotBlank())Text(error,color=MaterialTheme.colorScheme.error); Button(onClick={ if(verificationId==null){ if(!phone.matches(Regex("^\\+92[0-9]{10}$"))) error=invalidPhone else PhoneAuthProvider.verifyPhoneNumber(PhoneAuthOptions.newBuilder(auth).setPhoneNumber(phone).setTimeout(60,TimeUnit.SECONDS).setActivity(LocalContext.current as ComponentActivity).setCallbacks(object:PhoneAuthProvider.OnVerificationStateChangedCallbacks(){override fun onVerificationCompleted(c:com.google.firebase.auth.PhoneAuthCredential){auth.signInWithCredential(c).addOnSuccessListener{done()}.addOnFailureListener{error=failed}};override fun onVerificationFailed(e:com.google.firebase.FirebaseException){error=failed};override fun onCodeSent(id:String,t:PhoneAuthProvider.ForceResendingToken){verificationId=id}}).build()) } else auth.signInWithCredential(PhoneAuthProvider.getCredential(verificationId!!,code)).addOnSuccessListener{done()}.addOnFailureListener{error=failed} },modifier=Modifier.fillMaxWidth()){Text(if(verificationId==null)stringResource(R.string.send_code) else stringResource(R.string.verify_code))} } }
@Composable private fun Home(go:(Screen)->Unit) { Page(stringResource(R.string.welcome)){ Text(stringResource(R.string.welcome_body)); ActionCard(stringResource(R.string.donate),Icons.Outlined.VolunteerActivism){go(Screen.PROFILE)}; ActionCard(stringResource(R.string.request_blood),Icons.Outlined.Bloodtype){go(Screen.REQUEST)}; ActionCard(stringResource(R.string.directory),Icons.Outlined.LocalHospital){go(Screen.DIRECTORY)}; Spacer(Modifier.weight(1f)); TextButton({go(Screen.SETTINGS)},Modifier.align(Alignment.CenterHorizontally)){Text(stringResource(R.string.settings))} } }
@Composable private fun ActionCard(label:String, icon:androidx.compose.ui.graphics.vector.ImageVector, click:()->Unit)=ElevatedCard(Modifier.fillMaxWidth().clickable(onClick=click)){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null);Spacer(Modifier.width(16.dp));Text(label,fontWeight=FontWeight.SemiBold)}}
@Composable private fun Profile(repo:FirebaseRepository, done:()->Unit) { var name by remember{mutableStateOf("")};var cnic by remember{mutableStateOf("")};var dob by remember{mutableStateOf("")};var group by remember{mutableStateOf("O+")};var tehsil by remember{mutableStateOf("Nankana Sahib")};var declared by remember{mutableStateOf(false)};var notice by remember{mutableStateOf("")};val required=stringResource(R.string.required);val cnicError=stringResource(R.string.invalid_cnic);val ageError=stringResource(R.string.underage);val saved=stringResource(R.string.saved)
 Page(stringResource(R.string.profile),done){OutlinedTextField(name,{name=it},label={Text(stringResource(R.string.full_name))},modifier=Modifier.fillMaxWidth());OutlinedTextField(cnic,{cnic=it.filter(Char::isDigit).take(13)},label={Text(stringResource(R.string.cnic))},modifier=Modifier.fillMaxWidth());Text(stringResource(R.string.cnic_consent),style=MaterialTheme.typography.bodySmall);OutlinedTextField(dob,{dob=it},label={Text(stringResource(R.string.date_of_birth))},modifier=Modifier.fillMaxWidth());Choice(stringResource(R.string.blood_group),listOf("A+","A-","B+","B-","AB+","AB-","O+","O-"),group){group=it};Choice(stringResource(R.string.tehsil),listOf("Nankana Sahib","Sangla Hill","Shahkot","Warburton"),tehsil){tehsil=it};Row(verticalAlignment=Alignment.CenterVertically){Checkbox(declared,{declared=it});Text(stringResource(R.string.medical_eligibility),style=MaterialTheme.typography.bodySmall)};if(notice.isNotBlank())Text(notice);Button({when{ name.isBlank()||!declared->notice=required;cnic.length!=13->notice=cnicError;repo.age(dob)<17->notice=ageError;else->repo.saveProfile(name,cnic,dob,group,tehsil){notice=it?.localizedMessage?:saved}}},modifier=Modifier.fillMaxWidth()){Text(stringResource(R.string.save_profile))} } }
@Composable private fun Choice(label:String, entries:List<String>, selected:String, set:(String)->Unit) { var expand by remember{mutableStateOf(false)}; ExposedDropdownMenuBox(expand,{expand=it}){OutlinedTextField(selected,{},modifier=Modifier.menuAnchor().fillMaxWidth(),readOnly=true,label={Text(label)},trailingIcon={ExposedDropdownMenuDefaults.TrailingIcon(expand)});ExposedDropdownMenu(expand,{expand=false}){entries.forEach{DropdownMenuItem({Text(it)},{set(it);expand=false})}}} }
@Composable private fun Request(repo:FirebaseRepository,done:()->Unit) { var patient by remember{mutableStateOf("")};var group by remember{mutableStateOf("O+")};var units by remember{mutableStateOf(1)};var urgency by remember{mutableStateOf("Emergency")};var hospital by remember{mutableStateOf("DHQ Hospital Nankana Sahib")};var contact by remember{mutableStateOf("")};var note by remember{mutableStateOf("")};var error by remember{mutableStateOf("")};val required=stringResource(R.string.required);val sent=stringResource(R.string.saved)
 Page(stringResource(R.string.request_blood),done){OutlinedTextField(patient,{patient=it},label={Text(stringResource(R.string.patient_name))},modifier=Modifier.fillMaxWidth());Choice(stringResource(R.string.blood_group),listOf("A+","A-","B+","B-","AB+","AB-","O+","O-"),group){group=it};Text(stringResource(R.string.units));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf(1,2,3).forEach{FilterChip(it==units,{units=it},{Text("$it")})}};Choice(stringResource(R.string.urgency),listOf(stringResource(R.string.emergency),stringResource(R.string.within_24),stringResource(R.string.planned)),urgency){urgency=it};OutlinedTextField(hospital,{hospital=it},label={Text(stringResource(R.string.hospital))},modifier=Modifier.fillMaxWidth());OutlinedTextField(contact,{contact=it},label={Text(stringResource(R.string.contact_number))},modifier=Modifier.fillMaxWidth());OutlinedTextField(note,{note=it},label={Text(stringResource(R.string.note))},modifier=Modifier.fillMaxWidth());if(error.isNotBlank())Text(error);Spacer(Modifier.weight(1f));Button({if(patient.isBlank()||contact.isBlank())error=required else repo.createRequest(mapOf("patientName" to patient,"bloodGroup" to group,"units" to units,"urgency" to urgency,"hospital" to hospital,"contactNumber" to contact,"note" to note,"sos" to false)){error=it?.localizedMessage?:sent}},modifier=Modifier.fillMaxWidth()){Text(stringResource(R.string.send_request))};OutlinedButton({if(patient.isBlank()||contact.isBlank())error=required else repo.createRequest(mapOf("patientName" to patient,"bloodGroup" to group,"units" to units,"urgency" to stringResource(R.string.emergency),"hospital" to hospital,"contactNumber" to contact,"note" to note,"sos" to true)){error=it?.localizedMessage?:sent}},modifier=Modifier.fillMaxWidth()){Text(stringResource(R.string.send_sos))} } }
@Composable private fun Directory(repo:FirebaseRepository) { var hospitals by remember{mutableStateOf(emptyList<Hospital>())};DisposableEffect(Unit){val listener=repo.hospitals{hospitals=it};onDispose{listener.remove()}};Page(stringResource(R.string.directory)){if(hospitals.isEmpty())Text(stringResource(R.string.no_hospitals)) else LazyColumn(verticalArrangement=Arrangement.spacedBy(12.dp)){items(hospitals.size){i->val h=hospitals[i];ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(h.name,fontWeight=FontWeight.Bold);Text(h.address);if(h.phone.isNotBlank())Text(h.phone);if(h.stockStatus.isNotBlank())Text(h.stockStatus,style=MaterialTheme.typography.labelMedium)}}}}} }
@Composable private fun Settings(repo:FirebaseRepository,about:()->Unit,language:()->Unit)=Page(stringResource(R.string.settings)){ActionCard(stringResource(R.string.language),Icons.Outlined.Language,language);ActionCard(stringResource(R.string.about),Icons.Outlined.Info,about);Spacer(Modifier.weight(1f));OutlinedButton({repo.signOut();language()},modifier=Modifier.fillMaxWidth()){Text(stringResource(R.string.sign_out))}}
@Composable private fun About()=Page(stringResource(R.string.about)){Text(stringResource(R.string.credits_developed));Text(stringResource(R.string.credits_by));Text(stringResource(R.string.credits_contact))}
